### PR TITLE
Increment EVV4ESM version to latest release

### PR DESCRIPTION
**Pull request by mkstratos**
New version of EVV has more output for MVK test and uses a more statistically powerful correction method.

### CODE REVIEW

**Comment by xylar** [comment]
@mkstratos, I'm on vacation for the beginning of this week but I'll be glad to work with @altheaden to integrate this once I'm back on Thursday or Friday!

**Comment by xylar** [comment]
## Deployment
Deployed on:
- [ ] Andes/Frontier
- [ ] Anvil/Chrysalis
- [ ] Compy
- [ ] Perlmutter-CPU

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
I'll merge this tomorrow, once permissions have updated on Compy (very slow!)

**Comment by mkstratos** [comment]
Fantastic, thanks Xylar!

**Pull request merged**
