### PR TITLE
Update cime-env to evv v0.3.2 

### PR DESCRIPTION
**Pull request by mkstratos**
Fix for E3SM issue 4759 (https://github.com/E3SM-Project/E3SM/issues/4759)

### CODE REVIEW

**Comment by xylar** [comment]
Hi @mkstratos, I'll be getting back from vacation tomorrow and can deploy this.

**Comment by xylar** [comment]
I've deployed this on Anvil/Chrysalis and Compy so far.  I'll continue with the others very soon.  Sorry for the delay.

**Comment by mkstratos** [comment]
Looks good to me on Chrysalis. Thanks @xylar!

**Comment by xylar** [comment]
@mkstratos, permissions are still updating on Cooley but I have this installed on Anvil, Badger, Chrysalis, Cooley and Cori.  I no longer have permission to use Andes and won't be able to install there until early September.  But I also think that might not be a high-priority machine.

I'll merge this once Cooley is done unless you would like me to keep it open for some reason.

**Pull request merged**
