### PR TITLE
container definition and Travis CI config

### PR DESCRIPTION
**Pull request by rpwagner**
This adds a Singularity container definition file and basic Travis CI config. The Travis CI build will attempt to create a container using the recommend install command
```
conda create -n e3sm-unified-nox -c conda-forge -c e3sm -c cdat/label/v81 e3sm-unified mesalib
```

If it builds, it then does a simple execution test. The next feature should be some tests using the [Singularity `test` command](https://www.sylabs.io/guides/3.2/user-guide/cli/singularity_test.html).

### CODE REVIEW

**Comment by xylar** [comment]
@rpwagner, it would be great to add travis to this repo (whether that's through your account or one I create).

@rljacob, how would we go about doing that?  Who has admin permissions and would have the time to help get @rpwagner's travis-ci hooked to this repo?

**Comment by rljacob** [comment]
I've added both of you as admins to this repo.  I don't know how to set up Travis.

**Comment by rpwagner** [comment]
@xylar I'll set up Travis CI now. We can move it to your account later if that makes sense.

**Comment by xylar** [comment]
Thanks @rljacob.  @rpwagner, I'm not yet doing anything with my Travis CI account so easier to use yours if you've already go this going there.

**Comment by rpwagner** [comment]
@xylar are you ok with this being merged? After that I can set up a cron job in Travis to do a regular build of the repo to ensure that changes in the dependencies aren't tripping us up.

**Comment by xylar** [comment]
Looks good!  I just merged.

**Pull request merged**
