### PR TITLE
Pin the verison of distributed to match dask

### PR DESCRIPTION
**Pull request by xylar**
Bump build number

### CODE REVIEW

**Comment by xylar** [comment]
I uploaded new packages with this fix, so CI should work now.  I somehow didn't know that `dask` and `distributed` packages didn't automatically have the same version number.  I will see if that's a mistake in the conda build.

**Comment by xylar** [comment]
I have requested that the offending build of `distributed` be moved to broken: https://github.com/conda-forge/distributed-feedstock/issues/104

**Comment by xylar** [comment]
Oh, and hooray for CI doing its job and @rpwagner for making it happen!

**Comment by xylar** [comment]
BTW, we know that there are some issues with the OSX version of CDAT right now.  I'm working with them to fix it.  Shouldn't affect our CI because it's linux but if CDAT should cause trouble, we'll work on it.

**Comment by rpwagner** [comment]
It makes sense that it was a dependency, since things were find after the previous PR for changing the environment variables. Glad this is useful.

**Pull request merged**
