### PR TITLE
Update to v1.2.1

### PR DESCRIPTION
**Pull request by xylar**
The following packages are updated:
* mpas_analysis 1.0
* nco 4.7.5
* e3sm-diags 1.3.4
* libnetcdf 4.6.1
* livvkit 2.1.6
* processflow 2.0.2
* hdf5 1.10.2

### CODE REVIEW

**Comment by xylar** [comment]
I'd like to see if we can hold off on creating this version until processflow can be updated.  For now, we're having issues with NCL, see:
https://github.com/conda-forge/ncl-feedstock/issues/39

**Comment by xylar** [comment]
@zshaheen, is there a sanity check I can do to make sure e3sm_diags installed as expected, something like `python -c "import mpas_analysis"` or `livv --version`?

**Comment by zshaheen** [comment]
@xylar Yeah, you probably just do `python -c 'import acme_diags; print(acme_diags.__version__)'` to see what version, if any, is installed.

**Comment by sterlingbaldwin** [comment]
```processflow.py -v``` will give you the version number, but since goes through the whole argument parsing step it hits all the import statements, so if anything's missing it will give you an error.

**Comment by xylar** [comment]
Thanks @sterlingbaldwin and @zshaheen.  @zshaheen, I'm guessing `python -c 'import acme_diags'` would be a good basic check just to make sure the imports work right?  I don't actually need the version, I just want to be sure the package installed and there aren't library conflicts and such.

**Pull request merged**
