### PR TITLE
Fix cdat incompatibility with specified libnetcdf version

### PR DESCRIPTION
**Pull request by xylar**
This is accomplished by switching to cdms2 v. 3.0.1, which is on conda-forge rather than the cdat channel.

### CODE REVIEW

**Comment by xylar** [comment]
This PR is intended to address #18

**Comment by xylar** [comment]
@doutriaux1 and @zshaheen, could you both make versions of all cdat packages are the desired ones.  This PR is the one to update them in if not. Currently, they are:
```
    "cdat ==8.0" \
    "cdat_info ==8.0" \
    "distarray ==2.12.2" \
    "cdms2 ==3.0.1" \
    "cdtime ==3.0" \
    "cdutil ==8.0" \
    "genutil ==8.0" \
    "vtk-cdat ==8.0.1.8.0" \
    "dv3d ==8.0" \
    "vcs ==8.0" \
    "vcsaddons ==8.0" \
    "output_viewer ==1.2.5" \
    "wk ==8.0" \
    "thermo ==8.0" \
    "cdp ==1.3.3" \
    "e3sm_nex ==0.0.2" \
```

**Comment by zshaheen** [comment]
@xylar Sorry for the delay. Yeah, it all looks good. @doutriaux1 is on vacation for the next week, so I'd say that you can go ahead and deploy.

**Comment by xylar** [comment]
I am also updating to NCO v. 4.7.6, since it was released in the middle of me debugging this issue.

**Pull request merged**
