### PR TITLE
Update to e3sm-unified 1.2.0

### PR DESCRIPTION
**Pull request by xylar**
Updates to many package versions for v. 1.2.0

Change to a single install script for all machines.

### CODE REVIEW

**Comment by xylar** [comment]
This PR is a work in progress because this update will not be able to take place until a version of e3sm_diags and processflow are available that work with cdat v. 8.0.

**Comment by doutriaux1** [comment]
@xylar may I suggest adding https://anaconda.org/cdat/e3sm_nex code is at: https://github.com/CDAT/e3sm_nex

**Comment by xylar** [comment]
Sure. I need a package name, channel and version to pin (if any).

**Comment by xylar** [comment]
... which I can get from your link above. Sorry. Will add.

**Comment by doutriaux1** [comment]
@xylar it was in the  anaconda link above 😉 
pkg name: e3sm_nex
version: 0.0.1
channel: cdat

**Comment by xylar** [comment]
@doutriaux1, we just finally got libnetcdf 4.6.1 to build on conda-forge:
https://github.com/conda-forge/libnetcdf-feedstock
https://github.com/conda-forge/libnetcdf-feedstock/pull/41

This version has an important bug fix specifically included to address big NetCDF files produced by MPAS-Ocean in E3SM at high res.  But...

When I try to peg that version, I get:
```
  - libnetcdf==4.6.1
  - thermo==8.0 -> cdms2 -> libcf -> hdf5[version='1.8.17|1.8.17.*']
  - thermo==8.0 -> cdms2 -> libcf -> libnetcdf=4.4
```
I realize that `libnetcdf ==4.4.*` is the [official pinning for conda-forge](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml) so maybe we're going to have trouble.  But could you look into this and see if there's any way of relaxing the restrictions on cdat and its dependencies?  Otherwise there's no way for us to take advantage of the bug fix :-(

cc @czender

**Comment by pwolfram** [comment]
Thanks @xylar for getting in `tabulate` cc @vanroekel

**Comment by xylar** [comment]
I decided to up the version number to `1.2.0` because we're seeing some relatively significant changes in this update.  I will reserve `2.x.x` for versions of `e3sm-unified` that are compatible with E3SM v2.

**Comment by xylar** [comment]
Okay, thanks for the help @zshaheen and @doutriaux1.  I think the only thing were now waiting on is a version of `processflow` that is compatible with all the other changes here. (No pressure, @sterlingbaldwin.)

**Pull request merged**
