### PR TITLE
Update to v1.2.5

### LINKED ISSUE #36: Basemap not working in csh version
For some reason, the enviornment variable `PROJ_LIB` is not getting defined as part of `conda activate ...` in csh/tcsh/etc. (Thanks, @milenaveneziani, for pointing me to this issue.)

A solution may be to define this variable manually in the `load_latest...csh` script.

### PR DESCRIPTION
**Pull request by xylar**
Switches to using a `meta.yaml` build, which allows different dependencies for python 2 and python 3, as well as for OSX vs. linux.

Update versions of main packages to:
* `cdat` 8.1
* `e3sm_diags` 1.6.1
* `mpas-analysis` 1.2.3 (new name on conda-forge)
* `nco` 4.7.9
* `ilamb` 2.3.1 (py2.7), 2.4 (py3.7) (added)
* `processflow` 2.2.0
* `zstash` 0.2.0 (py2.7 only)

Updated dependencies to:
* `cdat_info` 8.1.1
* `distarray` 2.12.2
* `cdms2` 3.1.2
* `cdtime` 3.1.2
* `cdutil` 8.1
* `genutil` 8.1.1
* `vtk-cdat` 8.2.0rc2.8.1
* `dv3d` 8.1
* `vcs` 8.1
* `vcsaddons` 8.1
* `wk` 8.1
* `thermo` 8.1
* `e3sm_nex` 1.0.0
* `xarray` 0.11.3
* `dask` 1.1.3
* `nb_conda_kernels` (added)
* `libnetcdf` 4.6.2
* `hdf5` 1.10.4
* `eofs` 1.3.1
* `pywavelets`

Fixes an issue with the csh version of the conda environment on E3SM supported machines by explicitly setting an environment variable needed by `basemap`.

closes #36

### CODE REVIEW

**Comment by xylar** [comment]
Not ready to merge because 
* `zstash` and `mpas_analysis` versions are not yet released
* can't build with currently pinned `cdms2`, see #38

**Comment by xylar** [comment]
Almost there.  Waiting for https://github.com/E3SM-Project/e3sm_diags/pull/203 and the subsequent build to be uploaded to the `e3sm` channel.

The decision was made not to add `zstash` for now.

**Comment by xylar** [comment]
For my reference, here's the build command I used:
```
conda build --python=2.7 -c conda-forge -c e3sm -c cdat -c cdat/label/v81 -c defaults meta.yaml
```

**Comment by doutriaux1** [comment]
@xylar I would remove the `-c cdat` I'm trying to get away from this and tag/label each release.

**Comment by xylar** [comment]
@doutriaux1, that sounds good!  All I would need for me to be able to drop the `cdat` channel is for you to add `cdat/label/v81` to `e3sm_nex`.

**Comment by doutriaux1** [comment]
Done!

**Comment by xylar** [comment]
I appreciate it!

**Comment by xylar** [comment]
@doutriaux1, I'm getting a `ClobberWarning` from `libuuid` and `ossuuid` as well as `jupyter` and `jupyter_core`:
```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.a'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.la'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.so'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::libuuid-2.32.1-h14c3975_1000, conda-forge::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/pkgconfig/uuid.pc'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::jupyter_core-4.4.0-py_0, conda-forge::jupyter-1.0.0-py_1
  path: 'lib/python2.7/site-packages/jupyter.py'


ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::jupyter_core-4.4.0-py_0, conda-forge::jupyter-1.0.0-py_1
  path: 'lib/python2.7/site-packages/jupyter.pyc'
```
Is that anything you know something about?  I tried to find out more about `ossuuid` but its feedstock points to an FTP URL that is either down or doesn't exist.  Could it be one of your packages that brings in `ossuuid`?  If so, what about using `libuuid` instead or doing something to make sure the two don't conflict?

**Comment by doutriaux1** [comment]
@xylar are you bringing in cmor? I think cmor needs ossuuid. @dnadeau4 is cdms/libcdms using ossuuid? Or is it just cmor. I think it's just CMOR. If it's just CMOR then @mauzey1 could you please take a look into switching to libuuid? Thanks!

**Comment by xylar** [comment]
We will be bringing in CMOR thought `processflow` but that's not currently the case.  So it must be another package.  I'll try to track it down.

**Comment by xylar** [comment]
@doutriaux1, the dependency on `ossuuid` comes through `libcf`.  Is that one of yours?

**Comment by xylar** [comment]
https://github.com/conda-forge/libcf-feedstock/blob/master/recipe/meta.yaml#L32

**Comment by xylar** [comment]
The `jupyter`/`jupyter_core` has already been reported:
https://github.com/conda-forge/jupyter-feedstock/issues/4

Maybe not a critical problem but could break `jupyter`.  The proposed solution of installing `jupyter` from `defaults` isn't practical for us because it is a dependency of both `cdat` and an explicit dependency of `e3sm-unified`.

**Comment by doutriaux1** [comment]
yes. we'll try to update this in nightly

**Comment by xylar** [comment]
The `jupyter` issue should be resolved by https://github.com/conda-forge/jupyter-feedstock/pull/8

**Pull request merged**
